### ISSUE TITLE
[text ui] animation interferes with UI activation

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#85]
When selecting text I would expect that the rich text UI pops up but when switching the selection the disappear animation can interfere with the popup:

![rich-text-ui-issue-1](https://cloud.githubusercontent.com/assets/467450/19465305/f3081d76-94b7-11e6-8a93-f1f94ac74c35.gif)

Expected behavior when waiting long enough between (de)selection :

![rich-text-ui-issue-2](https://cloud.githubusercontent.com/assets/467450/19465313/ffdb5a40-94b7-11e6-922b-4ff1b7e0f9d0.gif)

I think the animation should not be able to interfere with triggering the popup at all, no matter what the timing is.

**Comment by merryman** [comment]
The problem here is as follows: Currently fadeOut is just an animation of the opacity property, which does not have an immediate 'morph removal effect' in the morphic model. This means that fade out will not remove the morph from the point it is triggered but only after the opacity has dropped to 0 entirely (using the onFinish animation callback). If we were to remove the morph immediately the virtual DOM will immediately unmount and remove a DOM node since it discovers that one is not longer required to be rendered. This effectively cancels the fading animation. 
In order to make a fade out animation that has an immediate effect in the DOM model we would need to devise a way that preserves DOM nodes in case they are being removed via a fade animation. That would require to make our animation interface fadeOut-aware, something I have not yet attempted and frankly sounds kind of involved for what we get from it.

For the time being I would suggest a temporary solution by adding a 'removed'-flag on the text ui widget, that immediately tells the interface that it has been conceptually removed from the world once the fadeOut animation has been triggered.
We could also decide to move this 'wasRemoved flag' into the Morphic kernel, making all getters aware that morphs marked as removed (due to active fading animations), should no longer be retrieved.

**Comment by rksm** [comment]
I think animation in the text widget doesn't really add anything, removing it solves the issue.
